name: iOS

on: push

jobs:
  unit-tests:
    runs-on: macos-15
    steps:
      - name: Get the code
        uses: actions/checkout@v7

      - name: Which Xcode is active
        run: xcodebuild -version

      - name: Resolve dependencies
        run: |
          xcodebuild -resolvePackageDependencies \
            -project "Rick&Morty.xcodeproj"

      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -project "Rick&Morty.xcodeproj" \
            -scheme "Rick&Morty" \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5'

      - name: Run tests
        run: |
          xcodebuild test-without-building \
            -project "Rick&Morty.xcodeproj" \
            -scheme "Rick&Morty" \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -only-testing:"Rick&MortyTests"
