name: iOS

on: push

jobs:
  unit-tests:
    runs-on: macos-15
    steps:
      - name: Get the code
        uses: actions/checkout@v7

      - name: Which Xcode is active
        run: xcodebuild -version

      - name: Cache SPM
        uses: actions/cache@v6
        with:
          path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
          key: spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: spm-

      - name: Run unit tests
        run: |
          xcodebuild test \
            -project "Rick&Morty.xcodeproj" \
            -scheme "Rick&Morty" \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.5' \
            -only-testing:"Rick&MortyTests"
